<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AVRequest.aspx.cs" Inherits="AdminPages_AVRequest" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="welcome" Runat="Server">
    <asp:Label ID="lblAvRequest" runat="server" Text="AV Reqeust" Font-Size="Large" Font-Bold ="true"></asp:Label>
    <asp:GridView ID="GridView1" runat="server" DataSourceID="avRequest"
        DataKeyNames="av_form_id" AutoGenerateColumns="false" AutoGenerateDeleteButton="true">
         <Columns>
            <asp:BoundField DataField="complaint_date" HeaderText="Complaint Date" ReadOnly="True" Visible="true" SortExpression="complaint_date"></asp:BoundField>
            <asp:BoundField DataField="first_name" HeaderText="First Name" ReadOnly="True" Visible="true" SortExpression="first_name"></asp:BoundField>
            <asp:BoundField DataField="last_name" HeaderText="Last Name" ReadOnly="True" Visible="true" SortExpression="last_name"></asp:BoundField>
            <asp:BoundField DataField="phone" HeaderText="Phone Number" ReadOnly="True" Visible="true" SortExpression="phone"></asp:BoundField>
            <asp:BoundField DataField="email" HeaderText="Email" ReadOnly="True" Visible="true" SortExpression="email"></asp:BoundField>
            <asp:BoundField DataField="room" HeaderText="Room Number" ReadOnly="True" Visible="true" SortExpression="room"></asp:BoundField>
            <asp:BoundField DataField="complaint" HeaderText="Complaint" ReadOnly="True" Visible="true" SortExpression="complaint"></asp:BoundField>
            

        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="avRequest" runat="server" ConnectionString="<%$ ConnectionStrings:UserDB %>" 
        SelectCommand ="SELECT * FROM AVFORM;" 
        DeleteCommand="DELETE FROM AVFORM WHERE av_form_id=@av_form_id;">
        <InsertParameters>
            <asp:Parameter Name="Complaint Date" />
            <asp:Parameter Name="First Name" />
            <asp:Parameter Name="Last Name" />
            <asp:Parameter Name="Phone Number" />
            <asp:Parameter Name="Email" />
            <asp:Parameter Name= "Room Number" />
            <asp:Parameter Name="Complaint" />

        </InsertParameters>
        
         <DeleteParameters>
            <asp:Parameter Name="av_form_id" />
        </DeleteParameters>
        
    </asp:SqlDataSource>
   
</asp:Content>

