<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="StudentRequest.aspx.cs" Inherits="AdminPages_StudentRequest" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="welcome" Runat="Server">

    <br /><br />
    <asp:Label ID="lblStudentRequest" runat="server" Text="Student Request Data" Font-Size="Large" Font-Bold="true"></asp:Label>
    <asp:GridView ID="GridView1" runat="server" DataSourceID="stdRequest" DataKeyNames="student_form_id"
         AutoGenerateColumns="false" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:BoundField DataField="first_name" HeaderText="First Name" ReadOnly="True" Visible="true" SortExpression="first_name"></asp:BoundField>
            <asp:BoundField DataField="last_name" HeaderText="Last Name" ReadOnly="True" Visible="true" SortExpression="last_name"></asp:BoundField>
            <asp:BoundField DataField="phone_number" HeaderText="Phone Number" ReadOnly="True" Visible="true" SortExpression="phone_number"></asp:BoundField>
            <asp:BoundField DataField="email" HeaderText="Email" ReadOnly="True" Visible="true" SortExpression="email"></asp:BoundField>
            <asp:BoundField DataField="neiu_id_number" HeaderText="NEIU Id Number" ReadOnly="True" Visible="true" SortExpression="neiu_id_number"></asp:BoundField>
            <asp:BoundField DataField="pickup_date" HeaderText="Pickup Date" ReadOnly="True" Visible="true" SortExpression="pickup_date"></asp:BoundField>
            <asp:BoundField DataField="return_date" HeaderText="Return Date" ReadOnly="True" Visible="true" SortExpression="return_date"></asp:BoundField>
            <asp:BoundField DataField="course_name" HeaderText="Course Name" ReadOnly="True" Visible="true" SortExpression="course_name"></asp:BoundField>
            <asp:BoundField DataField="professor_name" HeaderText="Professor Name" ReadOnly="True" Visible="true" SortExpression="professor_name"></asp:BoundField>
              <asp:BoundField DataField="comments" HeaderText="Comments" ReadOnly="True" Visible="true" SortExpression="comments"></asp:BoundField>
            

        </Columns>
   </asp:GridView>
    
    <asp:SqlDataSource ID="stdRequest" runat="server" ConnectionString="<%$ ConnectionStrings:UserDB %>"
            SelectCommand="SELECT *  FROM STUDENTFORM;" DeleteCommand="DElETE FROM STUDENTFORM WHERE student_form_id=@student_form_id;">
        <InsertParameters>
            <asp:Parameter Name="First Name" />
            <asp:Parameter Name="Last Name" />
            <asp:Parameter Name="Phone Number" />
            <asp:Parameter Name="Email" />
            <asp:Parameter Name="NEIU ID Number" />
            <asp:Parameter Name= "Pickup Date" />
            <asp:Parameter Name="Return Date" />
            <asp:Parameter Name="Course Name" />
            <asp:Parameter Name="Professor Name" />
            <asp:Parameter Name ="Comments" />
            
        </InsertParameters>  
        <DeleteParameters>
            <asp:Parameter Name="student_form_id" />
        </DeleteParameters>
        
    </asp:SqlDataSource>


</asp:Content>

