<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="VideoRequest.aspx.cs" Inherits="AdminPages_VideoRequest" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="welcome" Runat="Server">
       <br /><br />
    <asp:Label ID="lblVideoFrom" runat="server" Text="Video Request Data" Font-Size="Large" Font-Bold="true"></asp:Label>
    <asp:GridView ID="GridView1" runat="server" DataSourceID="stdRequest" DataKeyNames="video_form_id"
         AutoGenerateColumns="false" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:BoundField DataField="first_name" HeaderText="First Name" ReadOnly="True" Visible="true" SortExpression="first_name"></asp:BoundField>
            <asp:BoundField DataField="last_name" HeaderText="Last Name" ReadOnly="True" Visible="true" SortExpression="last_name"></asp:BoundField>
            <asp:BoundField DataField="phone_number" HeaderText="Phone Number" ReadOnly="True" Visible="true" SortExpression="phone_number"></asp:BoundField>
            <asp:BoundField DataField="date_of_recording" HeaderText="Date of Recording" ReadOnly="True" Visible="true" SortExpression="date_of_recording"></asp:BoundField>
            <asp:BoundField DataField="location" HeaderText="Location" ReadOnly="True" Visible="true" SortExpression="location"></asp:BoundField>
            <asp:BoundField DataField="DVD_label" HeaderText="DVD Label" ReadOnly="True" Visible="true" SortExpression="DVD_label"></asp:BoundField>
            <asp:BoundField DataField="format_type" HeaderText="Format Type" ReadOnly="True" Visible="true" SortExpression="format_type"></asp:BoundField>
            <asp:BoundField DataField="comments" HeaderText="Comments" ReadOnly="True" Visible="true" SortExpression="comments"></asp:BoundField>
            <asp:BoundField DataField="number_copies" HeaderText="Number Of Copies" ReadOnly="True" Visible="true" SortExpression="number_copies"></asp:BoundField>
            

        </Columns>
   </asp:GridView>
    
    <asp:SqlDataSource ID="stdRequest" runat="server" ConnectionString="<%$ ConnectionStrings:UserDB %>"
            SelectCommand="SELECT *  FROM VIDEOFORM;" DeleteCommand="DElETE FROM VIDEOFORM WHERE video_form_id=@video_form_id;">
        <InsertParameters>
            <asp:Parameter Name="First Name" />
            <asp:Parameter Name="Last Name" />
            <asp:Parameter Name="Phone Number" />
            <asp:Parameter Name="Date of Recording" />
            <asp:Parameter Name="Location" />
            <asp:Parameter Name= "DVD Label" />
            <asp:Parameter Name="Format Type" />
            <asp:Parameter Name="Comments" />
            <asp:Parameter Name="Number of Copies" />
            
        </InsertParameters>  
        <DeleteParameters>
            <asp:Parameter Name="video_form_id" />
        </DeleteParameters>
    </asp:SqlDataSource>
</asp:Content>

